


-- ----------------------------
-- Records of problem_tag
-- ----------------------------
INSERT INTO `problem_tag` VALUES ('1', 'c');
INSERT INTO `problem_tag` VALUES ('3', 'NOIP提高组2005');
INSERT INTO `problem_tag` VALUES ('4', '晴天小猪历险记');
INSERT INTO `problem_tag` VALUES ('5', '浙江2000清帝之惑');
INSERT INTO `problem_tag` VALUES ('6', '清帝之惑');
INSERT INTO `problem_tag` VALUES ('7', '上海2000清帝之惑');
INSERT INTO `problem_tag` VALUES ('8', 'IOI1994');
INSERT INTO `problem_tag` VALUES ('9', 'NOI2003');
INSERT INTO `problem_tag` VALUES ('10', 'CTSC1999');
INSERT INTO `problem_tag` VALUES ('11', 'Victoria的舞会');
INSERT INTO `problem_tag` VALUES ('12', 'NOIP普及组2005');
INSERT INTO `problem_tag` VALUES ('13', '送给圣诞夜的礼物');
INSERT INTO `problem_tag` VALUES ('14', 'WinterCamp2002');
INSERT INTO `problem_tag` VALUES ('15', '迎春舞会');
INSERT INTO `problem_tag` VALUES ('16', '新年趣事');
INSERT INTO `problem_tag` VALUES ('17', 'Sunnypig的奇幻之旅');
INSERT INTO `problem_tag` VALUES ('18', '湖南2005Sunnypig的奇幻之旅');
INSERT INTO `problem_tag` VALUES ('19', '小胖系列');
INSERT INTO `problem_tag` VALUES ('20', 'NOIP提高组2004');
INSERT INTO `problem_tag` VALUES ('21', 'NOIP提高组2003');
INSERT INTO `problem_tag` VALUES ('22', '湖南2004小胖系列');
INSERT INTO `problem_tag` VALUES ('23', 'NOIP普及组2004');
INSERT INTO `problem_tag` VALUES ('24', 'NOIP提高组2001');
INSERT INTO `problem_tag` VALUES ('25', 'NOIP普及组2002');
INSERT INTO `problem_tag` VALUES ('26', 'NOIP普及组2003');
INSERT INTO `problem_tag` VALUES ('27', 'NOIP提高组2002');
INSERT INTO `problem_tag` VALUES ('28', 'NOIP普及组2001');
INSERT INTO `problem_tag` VALUES ('29', '湖南2002小胖系列');
INSERT INTO `problem_tag` VALUES ('30', 'NOIP提高组2000');
INSERT INTO `problem_tag` VALUES ('31', '野猫江米');
INSERT INTO `problem_tag` VALUES ('32', '三国争霸');
INSERT INTO `problem_tag` VALUES ('33', 'CTSC2000');
INSERT INTO `problem_tag` VALUES ('34', '浙江2006');
INSERT INTO `problem_tag` VALUES ('35', 'AsukaNoKaze\'s Retiring Problem');
INSERT INTO `problem_tag` VALUES ('36', 'NOIP提高组1999');
INSERT INTO `problem_tag` VALUES ('37', '柯南之Vijos被黑事件');
INSERT INTO `problem_tag` VALUES ('38', '星际青蛙');
INSERT INTO `problem_tag` VALUES ('39', '红色警戒');
INSERT INTO `problem_tag` VALUES ('40', '四川2005');
INSERT INTO `problem_tag` VALUES ('41', 'CQF');
INSERT INTO `problem_tag` VALUES ('42', '安徽2002');
INSERT INTO `problem_tag` VALUES ('43', '@.@');
INSERT INTO `problem_tag` VALUES ('44', '天使的施舍');
INSERT INTO `problem_tag` VALUES ('45', 'OIBH杯NOIP2006模拟赛');
INSERT INTO `problem_tag` VALUES ('46', 'IOI2000');
INSERT INTO `problem_tag` VALUES ('47', 'Wind~机器人系列');
INSERT INTO `problem_tag` VALUES ('48', '广东2001');
INSERT INTO `problem_tag` VALUES ('49', '仙剑系列');
INSERT INTO `problem_tag` VALUES ('50', '上海2002');
INSERT INTO `problem_tag` VALUES ('51', 'OIBH杯NOIP2006第二次模拟赛');
INSERT INTO `problem_tag` VALUES ('52', 'NOI1999');
INSERT INTO `problem_tag` VALUES ('53', 'NOI2000');
INSERT INTO `problem_tag` VALUES ('54', '黑皮的舞蹈');
INSERT INTO `problem_tag` VALUES ('55', 'NOIP提高组2006');
INSERT INTO `problem_tag` VALUES ('56', 'NOIP普及组2006');
INSERT INTO `problem_tag` VALUES ('57', '上海2001');
INSERT INTO `problem_tag` VALUES ('58', 'NOIP普及组1999');
INSERT INTO `problem_tag` VALUES ('59', '数独');
INSERT INTO `problem_tag` VALUES ('60', 'NOIP普及组2000');
INSERT INTO `problem_tag` VALUES ('61', 'NOI2006');
INSERT INTO `problem_tag` VALUES ('62', 'NOIP普及组2007');
INSERT INTO `problem_tag` VALUES ('63', 'NOIP提高组2007');
INSERT INTO `problem_tag` VALUES ('64', '时代中学');
INSERT INTO `problem_tag` VALUES ('65', 'Super pig杯NOIp2008提高组模拟赛');
INSERT INTO `problem_tag` VALUES ('66', '怪盗基德 VS OIBH');
INSERT INTO `problem_tag` VALUES ('67', 'IOI2007');
INSERT INTO `problem_tag` VALUES ('68', '四川2008');
INSERT INTO `problem_tag` VALUES ('69', '怪盗基德-忧郁的生日');
INSERT INTO `problem_tag` VALUES ('70', 'Colorful Valentine\'s Day');
INSERT INTO `problem_tag` VALUES ('71', 'F1');
INSERT INTO `problem_tag` VALUES ('72', 'Orz教主');
INSERT INTO `problem_tag` VALUES ('73', '中学生论坛');
INSERT INTO `problem_tag` VALUES ('74', '十八居士的白日梦');
INSERT INTO `problem_tag` VALUES ('75', 'CSCII');
INSERT INTO `problem_tag` VALUES ('76', 'NOI2002');
INSERT INTO `problem_tag` VALUES ('77', 'CSC WorkGroup III');
INSERT INTO `problem_tag` VALUES ('78', '重游SC theme Park');
INSERT INTO `problem_tag` VALUES ('79', 'NOIP提高组1997');
INSERT INTO `problem_tag` VALUES ('80', 'csapc');
INSERT INTO `problem_tag` VALUES ('81', 'CSC WorkGroup');
INSERT INTO `problem_tag` VALUES ('82', 'NOIP普及组2008');
INSERT INTO `problem_tag` VALUES ('83', '笨笨工作室系列');
INSERT INTO `problem_tag` VALUES ('84', 'NOIP提高组2008');
INSERT INTO `problem_tag` VALUES ('85', 'curimit');
INSERT INTO `problem_tag` VALUES ('86', 'NOI2004');
INSERT INTO `problem_tag` VALUES ('87', 'NOI2007');
INSERT INTO `problem_tag` VALUES ('88', 'zgx');
INSERT INTO `problem_tag` VALUES ('89', 'IOI2005');
INSERT INTO `problem_tag` VALUES ('90', '重庆2009');
INSERT INTO `problem_tag` VALUES ('91', 'NOI2001');
INSERT INTO `problem_tag` VALUES ('92', 'WinterCamp2001');
INSERT INTO `problem_tag` VALUES ('93', 'CTSC2002');
INSERT INTO `problem_tag` VALUES ('94', '山东2009');
INSERT INTO `problem_tag` VALUES ('95', '浙江2009');
INSERT INTO `problem_tag` VALUES ('96', '江苏2009');
INSERT INTO `problem_tag` VALUES ('97', '广东2009');
INSERT INTO `problem_tag` VALUES ('98', 'YYHS训练题');
INSERT INTO `problem_tag` VALUES ('99', 'IOI1996');
INSERT INTO `problem_tag` VALUES ('100', 'NOIP提高组1998');
INSERT INTO `problem_tag` VALUES ('101', 'NOIP普及组1998');
INSERT INTO `problem_tag` VALUES ('102', 'NOI2009');
INSERT INTO `problem_tag` VALUES ('103', '怪盗基德-月下の谜');
INSERT INTO `problem_tag` VALUES ('104', 'CTSC2001');
INSERT INTO `problem_tag` VALUES ('105', 'HOI');
INSERT INTO `problem_tag` VALUES ('106', '工藤新一への挑戰狀');
INSERT INTO `problem_tag` VALUES ('107', '天才的talent');
INSERT INTO `problem_tag` VALUES ('108', 'ORZ5');
INSERT INTO `problem_tag` VALUES ('109', 'WinterCamp2004');
INSERT INTO `problem_tag` VALUES ('110', 'OrzTky');
INSERT INTO `problem_tag` VALUES ('111', 'Lwins.');
INSERT INTO `problem_tag` VALUES ('112', 'NOI2005');
INSERT INTO `problem_tag` VALUES ('113', '陶陶');
INSERT INTO `problem_tag` VALUES ('114', 'Island Fantasy.,');
INSERT INTO `problem_tag` VALUES ('115', '微观世界奇遇记');
INSERT INTO `problem_tag` VALUES ('116', '初音未来_Miku');
INSERT INTO `problem_tag` VALUES ('117', 'NOI2011');
INSERT INTO `problem_tag` VALUES ('118', 'NOI2012');
INSERT INTO `problem_tag` VALUES ('119', 'NOI2010');
INSERT INTO `problem_tag` VALUES ('120', 'NOIP提高组2011');
INSERT INTO `problem_tag` VALUES ('121', 'YYB的OI之路');
INSERT INTO `problem_tag` VALUES ('122', 'NOIP提高组2009');
INSERT INTO `problem_tag` VALUES ('123', 'NOIP普及组2011');
INSERT INTO `problem_tag` VALUES ('124', 'NOIP提高组2010');
INSERT INTO `problem_tag` VALUES ('125', 'NOIP提高组2012');
INSERT INTO `problem_tag` VALUES ('126', 'NOIP普及组2010');
INSERT INTO `problem_tag` VALUES ('127', 'NOIP普及组2012');
INSERT INTO `problem_tag` VALUES ('128', 'NOIP普及组2009');
INSERT INTO `problem_tag` VALUES ('129', 'NOI2008');
INSERT INTO `problem_tag` VALUES ('130', 'NOIP提高组2013');
INSERT INTO `problem_tag` VALUES ('131', 'NOIP普及组2013');
INSERT INTO `problem_tag` VALUES ('132', '上海2012');
INSERT INTO `problem_tag` VALUES ('133', '天津2014');
INSERT INTO `problem_tag` VALUES ('134', '北京2014');
INSERT INTO `problem_tag` VALUES ('135', 'NOI2014');
INSERT INTO `problem_tag` VALUES ('136', '山东2014');
INSERT INTO `problem_tag` VALUES ('137', 'NOIP提高组2014');
INSERT INTO `problem_tag` VALUES ('138', 'NOIP普及组2014');
